#!/usr/bin/env python3
"""Build the consolidated, deduped SEO backlog from the 113 raw specialist findings.
Each item merges cross-agent duplicates and carries the six 1-5 scoring fields the
score-opportunities.py model expects (priority = bv*so*gap*conf / (effort+risk)).
Scores are orchestrator judgements anchored to the three commercial priorities
(1 roast/food, 2 private hire, 3 events) and the without-data track (no GSC/GA4/CWV).
"""
import json, os

# id, category, what, why, owner, source_roles, bv, so, gap, conf, eff, risk, bucket, deps
R = []
def add(id, cat, what, why, owner, src, bv, so, gap, conf, eff, risk, bucket, deps=""):
    R.append({
        "id": id, "category": cat, "what": what, "why": why, "owner": owner,
        "source": src, "business_value": bv, "search_opportunity": so,
        "current_performance_gap": gap, "confidence": conf, "effort": eff,
        "risk": risk, "bucket": bucket, "dependencies": deps,
    })

# ---- MEASUREMENT / TRACKING (Tier-1 prerequisites) ----
add("SEO-001","Measurement","Verify & set GA4 Measurement Protocol env vars (GA4_MEASUREMENT_ID/GA4_API_SECRET) in Vercel; confirm /api/analytics stops no-op'ing","Server-side conversion forwarding silently no-ops when unset (documented behaviour); bookings under-attributed since June. Every downstream ROI claim depends on this.","Owner+Dev","strategy#71, analytics#3, tracking-evidence.md",5,2,5,4,1,1,"Do now")
add("SEO-002","Measurement","Link/verify the GSC property and start weekly Performance + Page-Indexing exports; connect GA4","No verified GSC feed this run — no demand/position/CTR/indexation data. Blocks striking-distance, cannibalisation-by-data, hotel-page disposition and all Stage-9 re-measurement. This is the meta-blocker for the next audit's with-data track.","Owner","strategy#72, analytics#1, analytics#2, technical#83, authority#23",5,4,5,5,1,1,"Do now")
add("SEO-003","Measurement","Confirm the 5 commercial GTM/GA4 events are marked as GA4 key events; verify container triggers & SPA page_view","Tracking code is wired in components, but GTM container config + GA4 key-event marking are unverifiable without access — conversions may not register as key events. Assume absent until proven.","Owner+Dev","analytics#0, analytics#12",5,2,4,4,2,1,"Do now")
add("SEO-004","Measurement","Set NEXT_PUBLIC_META_PIXEL_ID at build time in Vercel (bundle-proven dead in production)","Meta Pixel never inlines at build, so paid/social conversion tracking is dead while Clarity's ID inlines fine. Cheap fix, real attribution loss.","Owner","analytics#2(pixel)",3,1,5,5,1,1,"Do now")
add("SEO-005","Measurement","Add Consent Mode v2 (ad_user_data/ad_personalization) + move to consent-mode modelling instead of hard-gating events pre-dataLayer","Strict hard-gate drops every event for non-consenting visitors, undercounting conversions by an unknown rate with no modelling; Consent Mode v2 signals missing.","Dev","analytics#4, analytics#8",3,1,3,5,2,2,"Schedule")
add("SEO-006","Measurement","Swap ~13 raw mailto: and 14 raw tel: links to the tracked EmailLink/PhoneButton components","Untracked contact links on commercial + local-intent pages mean phone/email conversions are invisible in analytics.","Dev","analytics#7, analytics#9, ux-cro#101",2,1,3,5,2,1,"Schedule")

# ---- CONVERSION PATH / CRO (highest commercial) ----
add("SEO-007","CRO/Bug","Fix formatMenuPrice so the £ symbol renders on money pages (currently 'Roasted Turkey16', 'Dishes from 4.')","Live prices show with no currency on /sunday-roast, /food-menu, /book-table and leak into meta descriptions — undermines the #1 priority's key conversion pages. One-function fix, sitewide effect.","Dev","ux-cro#98, copywriter#44, strategy#75, technical(menu)",5,2,5,5,1,1,"Do now")
add("SEO-008","CRO/Bug","Point the /corporate-events hero 'Book Your Event' CTA at the enquiry flow, not the 20-cover restaurant table wizard","A priority conversion CTA sends corporate enquirers into the wrong (capacity-capped) funnel — enquiries lost at the hero.","Dev","ux-cro#100",4,1,5,5,1,1,"Do now")
add("SEO-009","CRO","Verify Christmas-parties enquiry delivery (MS Graph env vars) reaches a real inbox before the Jul-Oct booking window peaks","Enquiry delivery depends on Microsoft Graph env vars; if unset the enquiry may silently fail during the one season this page earns. A 'ranks but can't convert' path.","Owner+Dev","ux-cro#102",4,1,4,2,1,2,"Do now")
add("SEO-010","CRO","Replace non-SSOT/banned enquiry emails (info@, events@, parking@) with manager@the-anchor.pub across CTAs","SSOT: manager@the-anchor.pub is the ONLY correct email; info@theanchorpub.co.uk is explicitly banned/legacy. Enquiries to dead mailboxes = silent lead loss.","Dev","editor-qa#59",4,1,5,5,1,1,"Do now")
add("SEO-011","CRO","Surface the private-hire enquiry form above the cost-estimator drawer; add estimator config-load fallback (no dead end)","Priority-2 conversion is buried behind a drawer; an estimator config-load failure shows 'Unable to load calculator' with no enquiry route — a conversion dead end.","Dev","ux-cro#99, ux-cro#104",4,1,4,4,2,2,"Schedule")
add("SEO-012","CRO","Give the event SALES_CLOSED panel a real contact affordance (phone/email button), not just 'contact us if you need help'","Copy tells closed-sale visitors to contact us but offers nothing to click — dead end on event pages.","Dev","ux-cro#105",2,1,3,5,1,1,"Do now")
add("SEO-013","CRO","Add an above-the-fold conversion CTA to /restaurants-near-heathrow (hero omits the actions prop)","A priority near-Heathrow page has no visible CTA above the fold — traffic lands with nothing to do.","Dev","ux-cro#103",3,2,4,4,1,1,"Do now")
add("SEO-014","CRO","Make the global sticky CTA context-aware (enquiry on private-hire/christmas/wakes, not 'Book a table'); soften wakes 'Instant Quote' tone for bereaved visitors","One-size 'Book a table' bar pushes the wrong action on enquiry pages; 'Instant Quote & Check Availability' is tonally wrong for a wakes audience.","Dev","ux-cro#107, ux-cro#106",3,1,3,4,2,1,"Schedule")

# ---- CONTENT ACCURACY / SSOT (brand-critical) ----
add("SEO-015","Content/SSOT","Fix June price-scrub placeholders rendering as literal customer text ('live price' x9 on /christmas-parties; 'buffets priced from the live approved source' in engagement-parties meta)","Placeholder tokens are showing to customers on money pages — a visible quality failure that also lands in SERP snippets.","Dev+Editorial","editor-qa#58",5,1,5,5,2,1,"Do now")
add("SEO-016","Content/SSOT","Complete the price de-hardcoding sweep: 4 app pages + ~10 indexable blogs still quote fixed food/drink prices; add a drift-guard test","SSOT mandates all food/drink prices live from DB. Hardcoded prices drift stale and violate policy; the sweep half-landed in June. Route copy via editorial-team.","Dev+Editorial","content#28, editor-qa#62, copywriter#54, content#36, technical#85",4,1,4,5,3,2,"Schedule")
add("SEO-017","Content/SSOT","Christmas-parties: remove ~20 hardcoded prices + the '£45-£52 spend target' (SSOT bans min-spend wording); fix 'fifteen minutes from T2' (SSOT 11)","The page earns in the Jul-Oct window now; it violates live-pricing + no-minimum-spend rules and states a wrong terminal distance. Urgent, seasonal.","Editorial+Dev","copywriter#47, copywriter#48, copywriter#49",5,2,5,5,3,2,"Do now")
add("SEO-018","Content/SSOT","Correct /private-hire/wakes fact drift: capacity (50/60 → SSOT 26 seated / 10+–150) and crematorium distance ('5 min' → SSOT 10 min)","A winning niche serving a grief audience contradicts itself and the SSOT on capacity and drive time — erodes trust at a sensitive moment.","Editorial","copywriter#45, copywriter#46, editor-qa#61",4,1,5,5,2,1,"Do now")
add("SEO-019","Content/SSOT","Reconcile room-hire-fee wording across the private-hire cluster to the SSOT ('discuss on enquiry'; wakes = no charge; deposit £250)","Fee stated three contradictory ways across the P2 cluster; an answer engine could quote the wrong one.","Editorial","editor-qa#60",3,1,4,5,2,1,"Schedule")
add("SEO-020","Content/SSOT","Purge verbatim banned claims from blog corpus (beef dripping, rotating guest ales, baby changing, Sky Sports/'never show live sport' contradiction)","Banned claims (SSOT §14) live in indexable posts and contradict other pages — brand + answer-engine risk. Route via editorial-team.","Editorial","editor-qa#63, content#34, editor-qa#67, content#41",3,2,4,5,3,1,"Schedule")
add("SEO-021","Content/SSOT","Fix the sitewide internal-linking component claiming '5 minutes from all terminals' (SSOT: 7-12 min); template-level","Every page inheriting the component repeats a wrong, over-claimed distance — systemic accuracy defect.","Dev","editor-qa#64",3,2,4,5,1,1,"Do now")
add("SEO-022","Content/SSOT","Remove hardcoded opening hours + review count from evergreen copy; pull from live source; reconcile occasion-page capacity claims to SSOT","Hardcoded hours/counts drift; sibling occasion pages disagree on capacity with no SSOT basis.","Editorial+Dev","editor-qa#65, editor-qa#66",2,1,3,5,2,1,"Schedule")

# ---- TITLES / METADATA (systemic) ----
add("SEO-023","Metadata/System","Rework the title template so it never double-appends the brand and keeps titles <=60 chars; give the homepage a branded title","211/240 titles exceed 60 chars (median 81) and 102 stack 'The Anchor' twice → sitewide SERP truncation; homepage title carries no brand. NOTE: 'The Anchor Pub' in titles is SSOT-PERMITTED (line 20) — the defect is length/doubling, not a banned phrase.","Dev","strategy#74, content#26, content#27, copywriter#43, copywriter#52",3,3,4,5,2,2,"Schedule")
add("SEO-024","Metadata","Rewrite the broken/oversized money-page meta descriptions (/private-hire 289-char broken; /food-menu, /book-table £-loss once SEO-007 lands)","Broken metas on money pages waste SERP real estate and read as low quality.","Editorial","strategy#75, copywriter#50",3,2,4,5,2,1,"Schedule","SEO-007")

# ---- TECHNICAL / CRAWL / SCHEMA ----
add("SEO-025","Technical","Re-point the two legacy /blog/best-*-near-heathrow 301s away from the noindexed merge target to /restaurants-near-heathrow; apply the tag-alias map at render so ~35-60 internal links stop hitting redirects","Legacy food-near-Heathrow link equity is being discarded into a noindex page; internal links waste crawl on redirects.","Dev","technical#81, technical#87, content#32, content#39",3,3,4,5,2,2,"Schedule")
add("SEO-026","Technical","Fix the hard 404 /menus 'View Menu' link on /live-sport/world-cup (point to /food-menu)","A 404 on a real navigational link wastes clicks and crawl.","Dev","technical#82, content#38",2,1,4,5,1,1,"Do now")
add("SEO-027","Technical/SSOT","/drinks: stop emitting 146 empty-price Offers and remove 32 hardcoded cocktail prices in content/menu/drinks.json; trim the 60KB JSON-LD","Invalid empty-price Offers + SSOT price violation + payload bloat on a menu page.","Dev","technical#85, strategy#78(part)",2,2,4,5,2,2,"Schedule")
add("SEO-028","Technical/Schema","Repair the schema estate: 430 blocks missing required fields (Restaurant address etc.); drop/trim retired-rich-result FAQ/HowTo bloat and 24-27KB blog articleBody; fix dangling @id refs","576 actionable schema rows collapse to ~5 template causes; fixing them is one template pass, not 236 page edits. Route structured-data design to schema-markup.","Dev","strategy#78, technical#88, technical#95, technical#89",2,2,3,4,3,2,"Schedule")
add("SEO-029","Technical","Turn off Cloudflare Email Address Obfuscation (Scrape Shield) — it creates 244 links to a /cdn-cgi 404 and hides the contact email from AI crawlers","Obfuscation breaks the email for AI answer engines and generates hundreds of 404 links. Owner toggle in Cloudflare.","Owner","technical#86",2,2,3,5,1,1,"Do now")
add("SEO-030","Technical/Perf","Serve right-sized og:images (the 290KB default shared by 120 pages + 226-322KB source JPGs) via the image pipeline","'163 oversized images' root-causes to raw og:image source files, not next/image heroes — a template/default-asset fix.","Dev","technical#84, ux-cro#111",2,1,3,4,2,1,"Schedule")
add("SEO-031","Technical","Fix robots.txt path (/leave-a-review → /leave-review) and collapse the ~473x-linked 3-hop /leave-review redirect chain","robots protects the wrong path; the review CTA is linked sitewide through a 3-hop redirect.","Dev","strategy#77, technical#91",2,1,3,5,1,1,"Do now")
add("SEO-032","Technical","Reconcile the sitemap: 44 crawled pages absent (incl. sweepstake), regenerate to cover indexable routes, and replace rolling new Date() lastmod with real dates","Sitemap shrank vs June and omits indexable pages; rolling lastmod is a false freshness signal.","Dev","strategy#79, technical#90, technical#92",2,2,3,4,2,1,"Schedule")
add("SEO-033","Technical","Delete the dead generateEventSchema helper that hardcodes quiz £3 / bingo £10 before anything imports it","Latent SSOT price violation waiting to ship; safe deletion now.","Dev","technical#93",1,1,2,5,1,1,"Monitor")

# ---- CONTENT ARCHITECTURE / CANNIBALISATION (GSC/keyword-plan gated) ----
add("SEO-034","Architecture","De-cannibalise /private-hire vs /function-room-hire vs /private-party-venue (interim retarget H1/title now; merge decision needs GSC + keyword-plan)","Three P2 money pages fight one head term. Interim differentiation is safe; a merge is high-risk and needs first-party data.","Editorial+Dev","strategy#76, content#29, copywriter#51",3,3,3,3,3,3,"Schedule","SEO-002")
add("SEO-035","Architecture","Resolve the 11 near-duplicate hotel-proximity pages (June R2): differentiate with verified per-hotel data or consolidate to the template hub","Doorway-page risk; only slug/name vary. Disposition needs GSC to see which earn.","Editorial+Dev","content#30, technical#94",2,2,3,3,3,3,"Schedule","SEO-002")
add("SEO-036","Architecture","Merge/differentiate the duplicate family-dining pages and the three competing function-room-cost blogs","Self-competition across near-identical pages/posts dilutes the target term.","Editorial","content#33, content#35, editor-qa#69",2,2,3,3,3,2,"Schedule","SEO-002")
add("SEO-037","AEO/Content","Add FAQ + FAQPage schema and reusable extractable answer blocks to /private-hire and /whats-on (route to ai-seo + schema-markup)","P2 money page has no FAQ/answer blocks; answer-engine citation upside on roast/private-hire/plane-spotting queries is unclaimed.","Editorial+Dev","content#31, content#40",3,3,3,4,3,1,"Schedule")

# ---- AUTHORITY (owner-executable, no backlink data) ----
add("SEO-038","Authority","Fix the inapub.co.uk listing (remove the banned 'Sky TV' claim, add a website link)","A third-party listing repeats a banned claim and drops a citation link — reputation + NAP fix, owner can do it.","Owner","authority#13",2,2,4,5,1,1,"Do now")
add("SEO-039","Authority","Claim the plane-spotting citation layer: SpottersWiki LHR, FlyerTalk beer-gardens thread, layover guides","The site's own content dominates plane-spotting yet earns zero citations from the canonical community resources — the highest-fit link magnet for a page that already converts.","Owner","authority#14, authority#16, authority#19",3,3,4,4,3,1,"Schedule")
add("SEO-040","Authority","Get listed in Sunday-roast + near-Heathrow directories/roundups (bestsundayroast.co.uk, barguide.london T5 — currently listing competitor Three Magpies)","Aligned with priority #1; competitor holds the slot the pub should own.","Owner","authority#15",3,3,3,4,2,1,"Schedule")
add("SEO-041","Authority","Stand up a review-velocity routine through the existing /leave-review page to close the TripAdvisor volume gap vs Three Magpies","Steady review flow is durable local authority and defends the roast/near-Heathrow clusters.","Owner","authority#17",3,2,3,3,2,1,"Schedule")
add("SEO-042","Authority","Pursue village community links (smra.uk, stanwellmoor.org) + local press (SurreyLive Stanwell Moor coverage); audit & optimise Google Business Profile","Local relevance beats generic DR here; GBP + community/press are the cheapest durable authority.","Owner","authority#18, authority#24, authority#25",3,3,3,3,3,1,"Schedule")

# ---- MINOR / COSMETIC ----
add("SEO-043","Copy/CRO","Deduplicate the /sunday-roast roast list (shown twice) and reconcile the hero 'no booking' vs 'Book a Table' mixed message","Minor polish on the #1 page; reduces confusion, small effort.","Editorial+Dev","ux-cro#108, ux-cro#109",2,1,2,4,1,1,"Monitor")
add("SEO-044","Copy","Fix US spelling 'Recognized' in the enquiry form (British English)","Brand-voice defect on a conversion form.","Dev","ux-cro#110",1,1,2,5,1,1,"Monitor")
add("SEO-045","Technical","Revert /book-table launch-fortnight revalidate=1h (stale TODO past 22 May 2026) to the intended value","Expired launch hack still in prod; freshness/caching drift.","Dev","ux-cro#112",1,1,2,5,1,1,"Monitor")
add("SEO-046","Copy","Correct /whats-on frequency over-claims ('this week', 'weekly'), the /fish-and-chips-heathrow Staines-vs-Heathrow title mismatch, and undated savings claims on /heathrow-parking + /corporate-events","Cluster of small accuracy/over-claim tidy-ups; batch via editorial-team.","Editorial","copywriter#53, content#37, copywriter#55, copywriter#56",2,1,2,4,2,1,"Monitor")

out=os.path.dirname(os.path.abspath(__file__))
json.dump(R, open(os.path.join(out,'backlog.json'),'w'), indent=1, ensure_ascii=False)
print(f"Wrote backlog.json with {len(R)} consolidated items (from 113 raw findings).")
from collections import Counter
print("bucket (pre-score, orchestrator hint):", dict(Counter(x['bucket'] for x in R)))
print("category:", dict(Counter(x['category'].split('/')[0] for x in R)))
