#!/usr/bin/env node
// Run against scripts/nations-smoke-server.cjs only. Never accepts a remote URL.
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const { chromium } = require('playwright')
const { AxeBuilder } = require('@axe-core/playwright')
const base = 'http://127.0.0.1:3137'
const fixtureId = '10000000-0000-4000-8000-000000000001'
const output = process.argv[2] || '/tmp/nations-smoke'
async function main() {
  await fs.mkdir(output, { recursive: true })
  const control = await fetch(`${base}/__nations_test?outage=false&cancel=false`)
  assert.equal(control.status, 200, 'Isolated fixture server must be running')
  const before = (await control.json()).requests.length
  const browser = await chromium.launch({ headless: true })
  const evidence = { checks: [], screenshots: [], consoleErrors: [] }
  try {
    const context = await browser.newContext()
    await context.route('**/*', async route => {
      const url = new URL(route.request().url())
      if (url.hostname === '127.0.0.1') return route.continue()
      if (url.hostname === 'challenges.cloudflare.com' && url.pathname.includes('/api.js')) {
        return route.fulfill({ contentType: 'application/javascript', body: `window.turnstile={render:(e,o)=>{setTimeout(()=>o.callback('isolated-test-token'),0);return 'test-widget'},remove:()=>{},reset:()=>{},getResponse:()=> 'isolated-test-token',isExpired:()=>false,ready:f=>f(),execute:()=>{}}; const cb=new URL(document.currentScript.src).searchParams.get('onload');if(cb&&window[cb])window[cb]();` })
      }
      return route.abort()
    })
    const page = await context.newPage()
    page.setDefaultTimeout(15000)
    page.on('pageerror', error => evidence.consoleErrors.push(error.message))
    await page.goto(`${base}/live-sport/nations-championship`, { waitUntil: 'domcontentloaded', timeout: 60000 })
    await page.getByRole('heading', { name: 'Choose your game and book a table' }).waitFor()
    const reject = page.getByRole('button', { name: 'Reject All', exact: true })
    if (await reject.isVisible()) await reject.click()
    assert.equal(await page.title(), 'Nations Championship 2026 near Heathrow | The Anchor')
    assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'), 'https://www.the-anchor.pub/live-sport/nations-championship')
    const markup = await page.locator('script[type="application/ld+json"]').allTextContents()
    const schemas = markup.map(value => JSON.parse(value))
    assert.ok(schemas.some(value => value['@type'] === 'CollectionPage'))
    evidence.checks.push('Rendered title, canonical and JSON-LD')
    for (const width of [320, 375, 768, 1440]) {
      await page.setViewportSize({ width, height: 950 })
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `Overflow at ${width}px`)
      const file = `${output}/tournament-${width}.png`
      await page.screenshot({ path: file }); evidence.screenshots.push(file)
    }
    evidence.checks.push('No horizontal overflow at 320, 375, 768 and 1440 pixels')
    const accessibility = await new AxeBuilder({ page }).include('main').analyze()
    evidence.accessibility = accessibility.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => n.target) }))
    await page.getByLabel('Filter by team').selectOption('England')
    await page.getByText('0 fixtures shown', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'Show all fixtures', exact: true }).click()
    await page.getByText('1 fixture shown', { exact: true }).waitFor()
    evidence.checks.push('Team filter and reset')
    const validCalendar = await fetch(`${base}/api/nations-championship/calendar/${fixtureId}`)
    assert.equal(validCalendar.status, 200)
    assert.ok((await validCalendar.text()).includes('DTSTART:20261107T120000Z'))
    await page.setViewportSize({ width: 375, height: 950 })
    await page.locator('#fixtures').scrollIntoViewIfNeeded()
    await page.screenshot({ path: `${output}/fixture-mobile.png` })
    await page.getByRole('link', { name: 'Book a table for Italy v South Africa', exact: true }).first().click()
    await page.waitForURL('**/book-table?**')
    await page.getByRole('heading', { name: 'Book a table for Italy v South Africa', exact: true }).waitFor()
    assert.equal(await page.getByLabel('Date', { exact: true }).inputValue(), '2026-11-07')
    await page.getByRole('button', { name: 'Find a table', exact: true }).click()
    await page.getByText('Choose your time', { exact: true }).waitFor()
    assert.equal(await page.getByRole('button', { name: /^2pm/ }).count(), 0, 'No arrival after screening ends')
    await page.getByRole('button', { name: /^12pm,/ }).click()
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByLabel('Mobile Number').fill('07700900000')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByLabel('First Name', { exact: true }).fill('Isolated')
    await page.getByLabel('Last name (optional)').fill('Test')
    await page.getByLabel('Email address').fill('isolated@example.invalid')
    await page.getByLabel('Notes (optional)', { exact: true }).fill('Synthetic browser booking, no customer.')
    await page.getByRole('button', { name: 'Continue to review', exact: true }).click()
    await page.getByRole('checkbox', { name: /I understand The Anchor/ }).check()
    await page.getByRole('button', { name: 'Confirm booking', exact: true }).click()
    await page.getByText('ISOLATED-TEST-1', { exact: false }).first().waitFor()
    const after = await (await fetch(`${base}/__nations_test`)).json()
    assert.equal(after.requests.length, before + 1)
    const booking = after.requests.at(-1)
    assert.equal(booking.date, '2026-11-07')
    assert.ok(JSON.stringify(booking).includes(`Nations Championship: Italy v South Africa [${fixtureId}]`))
    evidence.checks.push('Real fixture link, available opening slot, form submission and confirmed mock booking with trusted game notes')
    await page.screenshot({ path: `${output}/booking-confirmed.png`, fullPage: true })
    const noJs = await browser.newContext({ javaScriptEnabled: false })
    const staticPage = await noJs.newPage()
    await staticPage.goto(`${base}/live-sport/nations-championship`, { waitUntil: 'domcontentloaded' })
    assert.ok((await staticPage.locator('main').innerText()).includes('You will miss the start'))
    assert.ok(await staticPage.getByRole('link', { name: 'Book a table for Italy v South Africa', exact: true }).count())
    evidence.checks.push('Fixtures, partial warning, food and booking link available without JavaScript')
    await noJs.close()
    await fetch(`${base}/__nations_test?cancel=true`)
    const cancelled = await fetch(`${base}/api/table-bookings`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-forwarded-for': '192.0.2.10' }, body: JSON.stringify({ phone: '07700900000', first_name: 'Isolated', date: '2026-11-07', time: '12:00', party_size: 2, purpose: 'food', fixture_id: fixtureId, notes: 'Synthetic cancellation check', _t: 10, turnstile_token: 'isolated-test-token' }) })
    assert.equal(cancelled.status, 409)
    assert.equal((await (await fetch(`${base}/__nations_test`)).json()).requests.length, before + 1)
    evidence.checks.push('Cancelled fixture rejected by real POST handler with zero additional upstream booking writes')
    await fetch(`${base}/__nations_test?cancel=false`)
    // Drop the first browser response after the real website POST completed its
    // simulated upstream write, then cancel the game before recovering.
    await page.goto(`${base}/book-table?fixture_id=${fixtureId}&date=2026-11-07`)
    await page.getByRole('heading', { name: 'Book a table for Italy v South Africa', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Find a table', exact: true }).click()
    await page.getByRole('button', { name: /^12pm,/ }).click()
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByLabel('Mobile Number').fill('07700900000')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByLabel('First Name', { exact: true }).fill('Recovery')
    await page.getByLabel('Last name (optional)').fill('Test')
    await page.getByLabel('Email address').fill('isolated@example.invalid')
    await page.getByLabel('Notes (optional)', { exact: true }).fill('Original recovery notes')
    await page.getByRole('button', { name: 'Continue to review', exact: true }).click()
    await page.getByRole('checkbox', { name: /I understand The Anchor/ }).check()
    await page.clock.install()
    await page.clock.fastForward(5000)
    let responseDropped = false
    let finishDroppedResponse
    const droppedResponse = new Promise(resolve => { finishDroppedResponse = resolve })
    await page.route(`${base}/api/table-bookings`, async route => {
      if (!responseDropped && !route.request().headers()['x-booking-replay-only']) {
        const completed = await route.fetch()
        assert.equal(completed.status(), 201, await completed.text())
        responseDropped = true
        await route.abort('failed')
        finishDroppedResponse()
        return
      }
      return route.continue()
    })
    await page.getByRole('button', { name: 'Confirm booking', exact: true }).click()
    await droppedResponse
    await page.getByRole('button', { name: 'Check previous booking attempt', exact: true }).waitFor()
    await fetch(`${base}/__nations_test?cancel=true`)
    await page.evaluate(() => window.dispatchEvent(new Event('focus')))
    await page.getByRole('button', { name: 'Check previous booking attempt', exact: true }).click()
    await page.getByText('ISOLATED-TEST-1', { exact: false }).first().waitFor()
    const recovered = await (await fetch(`${base}/__nations_test`)).json()
    assert.equal(recovered.requests.length, before + 2, 'Recovery must not create another booking')
    assert.ok(recovered.requests.at(-1).notes.endsWith('Original recovery notes'))
    evidence.checks.push('Lost response recovered after cancellation through actual browser and POST path, with no second booking')
    await page.screenshot({ path: `${output}/booking-recovered.png` })
    await fetch(`${base}/__nations_test?cancel=false`)
    await fetch(`${base}/__nations_test?outage=true`)
    await page.goto(`${base}/live-sport/nations-championship`)
    await page.getByRole('heading', { name: 'Screening details are unavailable' }).waitFor()
    assert.equal(await page.getByRole('link', { name: 'Book a table for Italy v South Africa', exact: true }).count(), 0)
    evidence.checks.push('Server feed outage gives honest fallback, no game booking promise')
    const calendar = await fetch(`${base}/api/nations-championship/calendar/${fixtureId}`)
    assert.equal(calendar.status, 503)
    await fetch(`${base}/__nations_test?outage=false`)
    assert.equal(evidence.consoleErrors.length, 0, 'Browser runtime errors')
    assert.equal(evidence.accessibility.length, 0, 'Accessibility violations')
  } finally {
    await fs.writeFile(`${output}/evidence.json`, JSON.stringify(evidence, null, 2))
    await browser.close()
    await fetch(`${base}/__nations_test?outage=false&cancel=false`)
  }
  console.log(JSON.stringify(evidence, null, 2))
}
main().catch(error => { console.error(error); process.exitCode = 1 })
